/**
 * Entitas Generated Classes for arpg
 *
 * do not edit this file
 */
module arpg {
  "use strict";

  import Pool = entitas.Pool;
  import Entity = entitas.Entity;
  import Matcher = entitas.Matcher;
  import ISystem = entitas.ISystem;
  import IMatcher = entitas.IMatcher;
  import IComponent = entitas.IComponent;

  export enum CoreComponentIds {
    Mouse,
    Avatar,
    PropLv1,
    Position,
    Forward,
    Move,
    CurrOrder,
    SkillArr,
    Me,
    MyTeam,
    Neutral,
    Enemy,
    TotalComponents
  }

  entitas.Entity.initialize(CoreComponentIds.TotalComponents, {"entities":200,"components":128});


  export class MouseComponent implements IComponent {
    public isTrigger:boolean;
    public x:number;
    public y:number;
  }
  export class AvatarComponent implements IComponent {
    public ui:GComponent;
  }
  export class PropLv1Component implements IComponent {
    public moveSpeed:number;
    public hpMax:number;
    public hp:number;
    public radii:number;
  }
  export class PositionComponent implements IComponent {
    public x:number;
    public y:number;
  }
  export class ForwardComponent implements IComponent {
    public degree:number;
  }
  export class MoveComponent implements IComponent {
    public kind:number;
    public to:IXY;
    public startFrame:number;
    public lifeFrame:number;
  }
  export class CurrOrderComponent implements IComponent {
    public order:OrderKind;
    public autoAttack:boolean;
    public target:ActionTarget;
  }
  export class SkillArrComponent implements IComponent {
    public skillArr:SkillStateComponent[];
  }
  export class MeComponent implements IComponent {
  }
  export class MyTeamComponent implements IComponent {
  }
  export class NeutralComponent implements IComponent {
  }
  export class EnemyComponent implements IComponent {
  }


  export class Pools {
    
    static _allPools:Array<Pool>;
    
    static get allPools():Array<Pool> {
      if (Pools._allPools == null) {
        Pools._allPools = [Pools.pool];
      }
      return Pools._allPools;
    }
    
    static _pool:Pool;
    
    static get pool():Pool {
      if (Pools._pool == null) {
        Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
        entitas.viewer.VisualDebugging.init(Pools._pool);
      }
    
      return Pools._pool;
    }
  }
}