/**
 * Entitas Generated Classes for arpg
 *
 * do not edit this file
 */
module arpg {
  "use strict";

  import Pool = entitas.Pool;
  import Entity = entitas.Entity;
  import Matcher = entitas.Matcher;
  import ISystem = entitas.ISystem;
  import IMatcher = entitas.IMatcher;
  import IComponent = entitas.IComponent;

  export enum CoreComponentIds {
    Mouse,
    Avatar,
    PropLv1,
    Position,
    Move,
    SkillNormal,
    TotalComponents
  }

  entitas.Entity.initialize(CoreComponentIds.TotalComponents, {"entities":200,"components":128});


  export class MouseComponent implements IComponent {
    public isTrigger:boolean;
    public x:number;
    public y:number;
  }
  export class AvatarComponent implements IComponent {
    public ui:GComponent;
  }
  export class PropLv1Component implements IComponent {
    public moveSpeed:number;
    public hpMax:number;
    public hp:number;
  }
  export class PositionComponent implements IComponent {
    public x:number;
    public y:number;
  }
  export class MoveComponent implements IComponent {
    public block:boolean;
    public kind:number;
    public toX:number;
    public toY:number;
    public startFrame:number;
    public lifeFrame:number;
  }
  export class SkillNormalComponent implements IComponent {
    public sid:number;
    public state:number;
    public statePhase:number;
  }


  export class Pools {
    
    static _allPools:Array<Pool>;
    
    static get allPools():Array<Pool> {
      if (Pools._allPools == null) {
        Pools._allPools = [Pools.pool];
      }
      return Pools._allPools;
    }
    
    static _pool:Pool;
    
    static get pool():Pool {
      if (Pools._pool == null) {
        Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents, false);
        entitas.viewer.VisualDebugging.init(Pools._pool);
      }
    
      return Pools._pool;
    }
  }
}