/**
 * Entitas Generated Extensions for arpg
 *
 * do not edit this file
 */
(function(){
  "use strict";
  var Bag = entitas.utils.Bag;
  var Pool = entitas.Pool;
  var Entity = entitas.Entity;
  var Matcher = entitas.Matcher;
  var SingleEntityException = entitas.SingleEntityException;
  var MouseComponent = arpg.MouseComponent;
  var FacadeComponent = arpg.FacadeComponent;
  var AvatarComponent = arpg.AvatarComponent;
  var PositionComponent = arpg.PositionComponent;
  var MoveComponent = arpg.MoveComponent;
  var CoreComponentIds = arpg.CoreComponentIds;
  /** @type {entitas.utils.Bag} */
  Entity._mouseComponentPool = new Bag();
  (function() {
    for (var i=0; i<128; i++) {
      Entity._mouseComponentPool.add(new MouseComponent());
    }
  })();
  Entity.clearMouseComponentPool = function() {
    Entity._mouseComponentPool.clear();
  };
  /** @type {{arpg.MouseComponent} */
  Object.defineProperty(Entity.prototype, 'mouse', {
    get: function() {
      return this.getComponent(CoreComponentIds.Mouse);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasMouse', {
    get: function() {
      return this.hasComponent(CoreComponentIds.Mouse);
    }
  });
  /**
   * @param {boolean} isTrigger
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Entity.prototype.addMouse = function(isTrigger, x, y) {
    var component = Entity._mouseComponentPool.size() > 0 ? Entity._mouseComponentPool.removeLast() : new MouseComponent();
    component.isTrigger = isTrigger;
    component.x = x;
    component.y = y;
    this.addComponent(CoreComponentIds.Mouse, component);
    return this;
  };
  /**
   * @param {boolean} isTrigger
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceMouse = function(isTrigger, x, y) {
    var previousComponent = this.hasMouse ? this.mouse : null;
    var component = Entity._mouseComponentPool.size() > 0 ? Entity._mouseComponentPool.removeLast() : new MouseComponent();
    component.isTrigger = isTrigger;
    component.x = x;
    component.y = y;
    this.replaceComponent(CoreComponentIds.Mouse, component);
    if (previousComponent != null) {
      Entity._mouseComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeMouse = function() {
    var component = this.mouse;
    this.removeComponent(CoreComponentIds.Mouse);
    Entity._mouseComponentPool.add(component);
    return this;
  };
  /** @type {entitas.utils.Bag} */
  Entity._facadeComponentPool = new Bag();
  (function() {
    for (var i=0; i<128; i++) {
      Entity._facadeComponentPool.add(new FacadeComponent());
    }
  })();
  Entity.clearFacadeComponentPool = function() {
    Entity._facadeComponentPool.clear();
  };
  /** @type {{arpg.FacadeComponent} */
  Object.defineProperty(Entity.prototype, 'facade', {
    get: function() {
      return this.getComponent(CoreComponentIds.Facade);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasFacade', {
    get: function() {
      return this.hasComponent(CoreComponentIds.Facade);
    }
  });
  /**
   * @param {Entity} myRoleReal
   * @param {Entity} myRolePretreat
   * @param {Entity} myRoleNet
   * @returns {entitas.Entity}
   */
  Entity.prototype.addFacade = function(myRoleReal, myRolePretreat, myRoleNet) {
    var component = Entity._facadeComponentPool.size() > 0 ? Entity._facadeComponentPool.removeLast() : new FacadeComponent();
    component.myRoleReal = myRoleReal;
    component.myRolePretreat = myRolePretreat;
    component.myRoleNet = myRoleNet;
    this.addComponent(CoreComponentIds.Facade, component);
    return this;
  };
  /**
   * @param {Entity} myRoleReal
   * @param {Entity} myRolePretreat
   * @param {Entity} myRoleNet
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceFacade = function(myRoleReal, myRolePretreat, myRoleNet) {
    var previousComponent = this.hasFacade ? this.facade : null;
    var component = Entity._facadeComponentPool.size() > 0 ? Entity._facadeComponentPool.removeLast() : new FacadeComponent();
    component.myRoleReal = myRoleReal;
    component.myRolePretreat = myRolePretreat;
    component.myRoleNet = myRoleNet;
    this.replaceComponent(CoreComponentIds.Facade, component);
    if (previousComponent != null) {
      Entity._facadeComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeFacade = function() {
    var component = this.facade;
    this.removeComponent(CoreComponentIds.Facade);
    Entity._facadeComponentPool.add(component);
    return this;
  };
  /** @type {entitas.utils.Bag} */
  Entity._avatarComponentPool = new Bag();
  (function() {
    for (var i=0; i<128; i++) {
      Entity._avatarComponentPool.add(new AvatarComponent());
    }
  })();
  Entity.clearAvatarComponentPool = function() {
    Entity._avatarComponentPool.clear();
  };
  /** @type {{arpg.AvatarComponent} */
  Object.defineProperty(Entity.prototype, 'avatar', {
    get: function() {
      return this.getComponent(CoreComponentIds.Avatar);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasAvatar', {
    get: function() {
      return this.hasComponent(CoreComponentIds.Avatar);
    }
  });
  /**
   * @param {GComponent} ui
   * @returns {entitas.Entity}
   */
  Entity.prototype.addAvatar = function(ui) {
    var component = Entity._avatarComponentPool.size() > 0 ? Entity._avatarComponentPool.removeLast() : new AvatarComponent();
    component.ui = ui;
    this.addComponent(CoreComponentIds.Avatar, component);
    return this;
  };
  /**
   * @param {GComponent} ui
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceAvatar = function(ui) {
    var previousComponent = this.hasAvatar ? this.avatar : null;
    var component = Entity._avatarComponentPool.size() > 0 ? Entity._avatarComponentPool.removeLast() : new AvatarComponent();
    component.ui = ui;
    this.replaceComponent(CoreComponentIds.Avatar, component);
    if (previousComponent != null) {
      Entity._avatarComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeAvatar = function() {
    var component = this.avatar;
    this.removeComponent(CoreComponentIds.Avatar);
    Entity._avatarComponentPool.add(component);
    return this;
  };
  /** @type {entitas.utils.Bag} */
  Entity._positionComponentPool = new Bag();
  (function() {
    for (var i=0; i<128; i++) {
      Entity._positionComponentPool.add(new PositionComponent());
    }
  })();
  Entity.clearPositionComponentPool = function() {
    Entity._positionComponentPool.clear();
  };
  /** @type {{arpg.PositionComponent} */
  Object.defineProperty(Entity.prototype, 'position', {
    get: function() {
      return this.getComponent(CoreComponentIds.Position);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasPosition', {
    get: function() {
      return this.hasComponent(CoreComponentIds.Position);
    }
  });
  /**
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Entity.prototype.addPosition = function(x, y) {
    var component = Entity._positionComponentPool.size() > 0 ? Entity._positionComponentPool.removeLast() : new PositionComponent();
    component.x = x;
    component.y = y;
    this.addComponent(CoreComponentIds.Position, component);
    return this;
  };
  /**
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Entity.prototype.replacePosition = function(x, y) {
    var previousComponent = this.hasPosition ? this.position : null;
    var component = Entity._positionComponentPool.size() > 0 ? Entity._positionComponentPool.removeLast() : new PositionComponent();
    component.x = x;
    component.y = y;
    this.replaceComponent(CoreComponentIds.Position, component);
    if (previousComponent != null) {
      Entity._positionComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * @returns {entitas.Entity}
   */
  Entity.prototype.removePosition = function() {
    var component = this.position;
    this.removeComponent(CoreComponentIds.Position);
    Entity._positionComponentPool.add(component);
    return this;
  };
  /** @type {entitas.utils.Bag} */
  Entity._moveComponentPool = new Bag();
  (function() {
    for (var i=0; i<128; i++) {
      Entity._moveComponentPool.add(new MoveComponent());
    }
  })();
  Entity.clearMoveComponentPool = function() {
    Entity._moveComponentPool.clear();
  };
  /** @type {{arpg.MoveComponent} */
  Object.defineProperty(Entity.prototype, 'move', {
    get: function() {
      return this.getComponent(CoreComponentIds.Move);
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Entity.prototype, 'hasMove', {
    get: function() {
      return this.hasComponent(CoreComponentIds.Move);
    }
  });
  /**
   * @param {MoveKindEnum} kind
   * @param {number} speed
   * @param {number} speedX
   * @param {number} speedY
   * @param {number} toX
   * @param {number} toY
   * @param {number} startFrame
   * @param {number} lifeFrame
   * @param {number} totalFrame
   * @returns {entitas.Entity}
   */
  Entity.prototype.addMove = function(kind, speed, speedX, speedY, toX, toY, startFrame, lifeFrame, totalFrame) {
    var component = Entity._moveComponentPool.size() > 0 ? Entity._moveComponentPool.removeLast() : new MoveComponent();
    component.kind = kind;
    component.speed = speed;
    component.speedX = speedX;
    component.speedY = speedY;
    component.toX = toX;
    component.toY = toY;
    component.startFrame = startFrame;
    component.lifeFrame = lifeFrame;
    component.totalFrame = totalFrame;
    this.addComponent(CoreComponentIds.Move, component);
    return this;
  };
  /**
   * @param {MoveKindEnum} kind
   * @param {number} speed
   * @param {number} speedX
   * @param {number} speedY
   * @param {number} toX
   * @param {number} toY
   * @param {number} startFrame
   * @param {number} lifeFrame
   * @param {number} totalFrame
   * @returns {entitas.Entity}
   */
  Entity.prototype.replaceMove = function(kind, speed, speedX, speedY, toX, toY, startFrame, lifeFrame, totalFrame) {
    var previousComponent = this.hasMove ? this.move : null;
    var component = Entity._moveComponentPool.size() > 0 ? Entity._moveComponentPool.removeLast() : new MoveComponent();
    component.kind = kind;
    component.speed = speed;
    component.speedX = speedX;
    component.speedY = speedY;
    component.toX = toX;
    component.toY = toY;
    component.startFrame = startFrame;
    component.lifeFrame = lifeFrame;
    component.totalFrame = totalFrame;
    this.replaceComponent(CoreComponentIds.Move, component);
    if (previousComponent != null) {
      Entity._moveComponentPool.add(previousComponent);
    }
    return this;
  };
  /**
   * @returns {entitas.Entity}
   */
  Entity.prototype.removeMove = function() {
    var component = this.move;
    this.removeComponent(CoreComponentIds.Move);
    Entity._moveComponentPool.add(component);
    return this;
  };
  /** @type {entitas.Matcher} */
  Matcher._matcherMouse=null;
  
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'Mouse', {
    get: function() {
      if (Matcher._matcherMouse == null) {
        Matcher._matcherMouse = Matcher.allOf(CoreComponentIds.Mouse);
      }
      
      return Matcher._matcherMouse;
    }
  });
  /** @type {entitas.Matcher} */
  Matcher._matcherFacade=null;
  
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'Facade', {
    get: function() {
      if (Matcher._matcherFacade == null) {
        Matcher._matcherFacade = Matcher.allOf(CoreComponentIds.Facade);
      }
      
      return Matcher._matcherFacade;
    }
  });
  /** @type {entitas.Matcher} */
  Matcher._matcherAvatar=null;
  
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'Avatar', {
    get: function() {
      if (Matcher._matcherAvatar == null) {
        Matcher._matcherAvatar = Matcher.allOf(CoreComponentIds.Avatar);
      }
      
      return Matcher._matcherAvatar;
    }
  });
  /** @type {entitas.Matcher} */
  Matcher._matcherPosition=null;
  
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'Position', {
    get: function() {
      if (Matcher._matcherPosition == null) {
        Matcher._matcherPosition = Matcher.allOf(CoreComponentIds.Position);
      }
      
      return Matcher._matcherPosition;
    }
  });
  /** @type {entitas.Matcher} */
  Matcher._matcherMove=null;
  
  /** @type {entitas.Matcher} */
  Object.defineProperty(Matcher, 'Move', {
    get: function() {
      if (Matcher._matcherMove == null) {
        Matcher._matcherMove = Matcher.allOf(CoreComponentIds.Move);
      }
      
      return Matcher._matcherMove;
    }
  });
  /** @type {entitas.Entity} */
  Object.defineProperty(Pool.prototype, 'mouseEntity', {
    get: function() {
      return this.getGroup(Matcher.Mouse).getSingleEntity();
    }
  });
  /** @type {arpg.MouseComponent} */
  Object.defineProperty(Pool.prototype, 'mouse', {
    get: function() {
      return this.mouseEntity.mouse;
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Pool.prototype, 'hasMouse', {
    get: function() {
      return this.mouseEntity != undefined;
    }
  });
  /**
   * @param {boolean} isTrigger
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Pool.prototype.setMouse = function(isTrigger, x, y) {
    if (this.hasMouse) {
      throw new SingleEntityException(Matcher.Mouse);
    }
    var entity = this.createEntity('Mouse');
    entity.addMouse(isTrigger, x, y);
    return entity;
  };
  /**
   * @param {boolean} isTrigger
   * @param {number} x
   * @param {number} y
   * @returns {entitas.Entity}
   */
  Pool.prototype.replaceMouse = function(isTrigger, x, y) {
    var entity = this.mouseEntity;
    if (entity == null) {
      entity = this.setMouse(isTrigger, x, y);
    } else {
      entity.replaceMouse(isTrigger, x, y);
    }
    return entity;
  };
  /**
   * @returns {entitas.Entity}
   */
  Pool.prototype.removeMouse = function() {
    this.destroyEntity(this.mouseEntity);
  };
  /** @type {entitas.Entity} */
  Object.defineProperty(Pool.prototype, 'facadeEntity', {
    get: function() {
      return this.getGroup(Matcher.Facade).getSingleEntity();
    }
  });
  /** @type {arpg.FacadeComponent} */
  Object.defineProperty(Pool.prototype, 'facade', {
    get: function() {
      return this.facadeEntity.facade;
    }
  });
  /** @type {boolean} */
  Object.defineProperty(Pool.prototype, 'hasFacade', {
    get: function() {
      return this.facadeEntity != undefined;
    }
  });
  /**
   * @param {Entity} myRoleReal
   * @param {Entity} myRolePretreat
   * @param {Entity} myRoleNet
   * @returns {entitas.Entity}
   */
  Pool.prototype.setFacade = function(myRoleReal, myRolePretreat, myRoleNet) {
    if (this.hasFacade) {
      throw new SingleEntityException(Matcher.Facade);
    }
    var entity = this.createEntity('Facade');
    entity.addFacade(myRoleReal, myRolePretreat, myRoleNet);
    return entity;
  };
  /**
   * @param {Entity} myRoleReal
   * @param {Entity} myRolePretreat
   * @param {Entity} myRoleNet
   * @returns {entitas.Entity}
   */
  Pool.prototype.replaceFacade = function(myRoleReal, myRolePretreat, myRoleNet) {
    var entity = this.facadeEntity;
    if (entity == null) {
      entity = this.setFacade(myRoleReal, myRolePretreat, myRoleNet);
    } else {
      entity.replaceFacade(myRoleReal, myRolePretreat, myRoleNet);
    }
    return entity;
  };
  /**
   * @returns {entitas.Entity}
   */
  Pool.prototype.removeFacade = function() {
    this.destroyEntity(this.facadeEntity);
  };
})();